### ISSUE TITLE
lx zone installation issue

### ISSUE THREAD

**Issue by kloczek** [omniosorg/illumos-omnios#1011]
Looks like after zone boot zone is looping in vnic registration and deregistration.
`zoneadm` shows that zone is in "ready" state which does not allow shutdown.

Exerythinng is explainet in https://illumos.topicbox.com/groups/omnios-discuss/Tef54c5d573098a70-Md5ce4483a6aafb8db3b63c2b

**Comment by citrus-it** [comment]
There are a number of things that post-September 2020 `systemd` does differently around mounting filesystems, which don't work with the lx brand. We should fix this to support new Linux distributions under LX.

**Comment by citrus-it** [comment]
@kloczek @Chewbakka-Wakka - I have a change open that should fix this. Once it passes review and testing it will be merged into the OmniOS bloody branch. If you're interested in testing a hotfix against the stable and LTS r151038, let me know and I can build one for you.
