### ISSUE TITLE
Requesting support for /etc/netgroups (not needing NIS for netgroups)

### ISSUE THREAD

**Issue by discard-this** [omniosorg/illumos-omnios#1014]
I have several NFS exports that go to so many hosts I can't list them on zfs sharenfs lines (meaning I have a mix of zfs shared and /etc/dfs/dfstab entries) plus there is always a high chance of error whenever updating all of them when a host is added/removed from the list.

It would be very helpful if https://www.illumos.org/issues/3163 were to get some traction. Being able to just list netgroup entries would greatly improve reliability.

thanks,
nomad

**Comment by mvwieringen** [comment]
I imported the patch from illumos-nexenta into illumos-omnios and after some conflict resolution things mostly apply. We probably need to do some post processing but it looks to be mostly doable.

**Comment by mvwieringen** [comment]
A hotfix with the current state of things is available and can be installed using the following command:

```
pkg apply-hot-fix --be-name=<whatever> https://hf.omnios.org/r38/3163_netgroup.p5p
```
You can check if things work using

```
getent netgroup <netgroupname>
```
See netgroup(4) for the syntax to use in /etc/netgroup

**Comment by discard-this** [comment]
I've created and tested a netgroup file on my test NFS server running 151038. My (very initial) testing seems happy so far. Lots more testing to do but I need to figure out what my procedure(s) will be.

Thanks for getting to this so quickly!

nomad

**Comment by citrus-it** [comment]
This is going to be in the next release of r151038, scheduled for w/c 12th of July 2021.
Thanks for the additional testing, @discard-this
