### ISSUE TITLE
Allow CARP in bhyve-zones

### ISSUE THREAD

**Issue by Benzebub** [omniosorg/illumos-omnios#1025]
When setting up CARP between two OpenBSD guests in bhyve with a VNIC each the multicast MAC-address gets filtered and the shared IP is not reachable.
Trying to add the multicast MAC-address as a secondary address using "dladm set-linkprop" on the VNIC it can only be set on one host.
Setting it on a second machine returns the following error:
dladm: warning: cannot set link property 'secondary-macs' on 'znic1': object already exists
Would it be possible to allow a MAC address to be shared among two hosts?

**Comment by sjorge** [comment]
On bloody CARP now works between 2 FreeBSD vms so I would assume it will work for OpenBSD too.

You need to switch to using the e1000 nics instead and set promiscphys to true.

```
root@jupiter:~# zadm show rcon1 | jq .net | sed 's/"mac-addr": .*/"mac-addr": "00:00:00:00:00:00"/g'
[
  {
    "global-nic": "ixgbe0",
    "mac-addr": "00:00:00:00:00:00"
    "physical": "rcon10",
    "promiscphys": "true",
    "vlan-id": "110"
  },
  {
    "global-nic": "ixgbe0",
    "mac-addr": "00:00:00:00:00:00"
    "physical": "rcon11",
    "vlan-id": "140"
  }
]
```

Then it works, but there is currently a bug #1039 though, but as long as you're not sending traffic from ON the host it self to the vm it should already be usable.
