### ISSUE TITLE
/usr/lib/smbsrv/smbd dumping core on startup

### ISSUE THREAD

**Issue by discard-this** [omniosorg/illumos-omnios#1033]
Host is running 151038. SMB services suddenly stopped. In debugging the problem I see the following in /var/svc/log/network-smb-server:default.log:

> [ Aug 12 06:30:35 Executing start method ("/usr/lib/smbsrv/smbd start"). ]
> smbd: smbd starting, pid 22478
> smbd: NetBIOS services disabled
> smbd: service initialized
> [ Aug 12 06:30:35 Method "start" exited with status 0. ]
> smbd_dc_monitor: online
> smbd_localtime_monitor: online
> @ Thu Aug 12 06:30:46 2021
> smbd.info: smbd_dc_update: [redacted]: located [redacted]
> [ Aug 12 06:31:46 Stopping because process dumped core. ]
> [ Aug 12 06:31:46 Executing stop method (:kill). ]

This was followed by multiple retry attempts - all with the same result - then ultimately giving up since the service was restarting too frequently.

I had to get things working again quickly so rebooted the host and it has been stable for the past hour.

**Comment by citrus-it** [comment]
The fix for this was included in r151038s
