### ISSUE TITLE
Panic during install of r151040g on Windows 11 Hyper-V

### ISSUE THREAD

**Issue by JohnConnett** [omniosorg/illumos-omnios#1120]
Host: Windows 11 Pro; Version 21H2; OS build 22000.527
Installation Media: omnios-r151040g.iso
VM Settings: Generation 2; Secure Boot disabled; Memory 8192 MB; 2 Virtual processors

To reproduce: start the VM and wait. The "Welcome to the OmniOS installer" is displayed; the countdown finishes and almost immediately panics.

This is a screen capture of the tail end of the boot log:

![OmniOS](https://user-images.githubusercontent.com/2997216/156380063-19d67af0-c8d3-460d-a3dd-0cb35da7a8a9.png)

I have attached a named pipe to COM1 using:
`Set-VMComPort -VMName atelier2 -Path \\.\pipe\atelier2-com1 -Number 1`
However, I am unfamiliar with the techniques to capture the serial console output.

The Hypervisior scheduler type is 0x4 (see below). This is the root scheduler which is the default on my system.
```
Get-WinEvent -FilterHashTable @{ProviderName="Microsoft-Windows-Hyper-V-Hypervisor"; ID=2} | select -First 1

   ProviderName: Microsoft-Windows-Hyper-V-Hypervisor

TimeCreated                     Id LevelDisplayName Message
-----------                     -- ---------------- -------
26/02/2022 15:10:42              2 Information      Hypervisor scheduler type is 0x4.

```

Happy to investigate further or provide more information.

Note, the following installation media can be installed successfully on the same VM:
1. Fedora-Workstation-Live-x86_64-35-1.2.iso (Secure Boot enabled)
2. ubuntu-21.10-desktop-amd64.iso (Secure Boot enabled)
3. FreeBSD-13.0-RELEASE-amd64-dvd1.iso (Secure Boot disabled)

**Comment by JohnConnett** [comment]
This is a screen capture of the tail end of the boot log with Verbose: On and kmdb Mode: Loaded
![OmniOS2](https://user-images.githubusercontent.com/2997216/156384248-1f92b335-092f-4153-af9f-75bb86c0c37a.png)

**Comment by mvwieringen** [comment]
As far as I know only version 1 of Hyper-V is supported on Omnios. I think there is an experimental patch for allowing TSC clock detection on Version 2 but that is highly experimental. I just checked that is patch is in bloody so you could try booting an bloody
image (but probably run into other problems then.)

**Comment by JohnConnett** [comment]
On 07/03/2022 10:54, Marco van Wieringen wrote:
>
> As far as I know only version 1 of Hyper-V is supported on Omnios. I 
> think there is an experimental patch for allowing TSC clock detection 
> on Version 2 but that is highly experimental. I just checked that is 
> patch is in bloody so you could try booting an bloody
> image (but probably run into other problems then.)
>
Very perceptive! This was with omnios-bloody-2202-02-18.iso:

[...]
mem = 8387488K (0x1ffee8000)
TSC calibrated using Hyper-V; freq is 3302 MHz
Using default device instance data
SMBIOS v3.1 loaded (1244 bytes)initialized model-specific module 
'cpu_ms.GenuineIntel' on chip 0 core 0 strand 0
root nexus = i86pc
pseudo0 at root
pseudo0 is /pseudo
scsi_vhci0 at root
scsi_vhci0 is /scsi_vhci
Reading Intel IOMMU boot options
pseudo-device: acpippm0
acpippm0 is ***@***.***
pseudo-device: ppm0
ppm0 is ***@***.***
ramdisk0 at root
ramdisk0 is /ramdisk
root on /ramdisk:a fstype ufs
/cpus (cpunex0) online
pseudo-device: dld0
dld0 is ***@***.***

Then doen't progress.

--
John Connett

**Comment by mvwieringen** [comment]
Yeah so its either set it to type 1 or use something like virtualbox for now. Don't think this will change anytime soon given
that its a personal project for an illumos contributor which might work one day no one only know when.

**Comment by JohnConnett** [comment]
Oops! It was omnios-bloody-2022-02-18.iso. Here's the uncensored output:
```
mem = 8387488K (0x1ffee8000)
TSC calibrated using Hyper-V; freq is 3302 MHz
Using default device instance data
SMBIOS v3.1 loaded (1244 bytes)initialized model-specific module 'cpu_ms.GenuineIntel' on chip 0 core 0 strand 0
root nexus = i86pc
pseudo0 at root
pseudo0 is /pseudo
scsi_vhci0 at root
scsi_vhci0 is /scsi_vhci
Reading Intel IOMMU boot options
pseudo-device: acpippm0
acpippm0 is /pseudo/acpippm@0
pseudo-device: ppm0
ppm0 is /pseudo/ppm@0
ramdisk0 at root
ramdisk0 is /ramdisk
root on /ramdisk:a fstype ufs
/cpus (cpunex0) online
pseudo-device: dld0
dld0 is /pseudo/dld@0
```

**Comment by JohnConnett** [comment]
Can confirm that r151040g installs and runs on VirtualBox 6.1 hosted on Ubuntu 21.10.

Hyper-V Gen2 support would be useful! I'll have a look at the bloody code although I've never worked on anything this early in the startup of an OS. Happy to help testing if it gets to that stage.

**Comment by hadfl** [comment]
Thanks to contributions from @jasonbking (https://www.illumos.org/issues/13961, PR #1132), the next OmniOS bloody build will include support for running under Hyper-V as a Gen 2 VM, with the limitations mentioned in that PR (serial console only).

The next build of installation media for bloody will have these pieces if you'd like to test, and also the new stable release (r151042) will be in its beta stage in the next few weeks. If you're interested in helping to test that, subscribe to the beta testing mailing list at https://list.omnios.org/subscription/form and we'll be sending links out when they're ready.
