### ISSUE TITLE
please backport the 38xx driver to '046

### ISSUE THREAD

**Issue by discard-this** [omniosorg/illumos-omnios#1482]
Thew newly released 38xx driver will be very useful to us. It would be great if it could be made available in the LTS release.

https://www.illumos.org/issues/16524

thanks,
nomad

**Comment by danmcd** [comment]
The only tricky part, and it's probably not that tricky, is that '046 doesn't contain the mpi header refactoring, so just cherry-picking the commit won't suffice; the header changes need to go elsewhere.

**Comment by danmcd** [comment]
Or maybe not?  I just tried `git cherry-pick` and it WORKED.

**Comment by discard-this** [comment]
I can test this on the same host I used to test in '050, should you need a test to be tested.

**Comment by danmcd** [comment]
Make sure @discard-this you're monitoring the PR #1483 for more.

**Comment by citrus-it** [comment]
Integrated with #1483
