### ISSUE TITLE
new lipkg zone unexpectedly was not linked from the outset

### ISSUE THREAD

**Issue by idodeclare** [omniosorg/illumos-omnios#159]
@idodeclare:
> Hello. I had an odd experience with a new lipkg zone yesterday. I created it as usual from the root with `zonecfg`/`zoneadm`, and then later in the day became aware of the r151024q update.

> From the root, though, `pkg update -r` would not work because of outdated pkg, but then neither `pkg install -r pkg:/package/pkg` nor `pkg install pkg:/package/pkg` would work because the new zone apparently was already on the new bits and was raising IPS exceptions concerning version.

@citrus-it:
> That is strange.. there was a pkg update in r151024q
did you manage to resolve it? You might have had to downgrade pkg in the zone
or, use `pkg update -f`

@idodeclare:
> Yes. Since that's rare, I wonder if there is a latent bug where new lipkg zones might get unexpectedly new bits.

> I.e. in violation of "linked" right off the bat even though the initial operations (`zonecfg`/`zoneadm`) happened from the root.

@citrus-it:
> yes, definitely worth further testing.

**Comment by citrus-it** [comment]
The main problem here is that the GZ version of `pkg` appears to have not been the latest so a later version ended up installed in the zone. We should constrain the zone version of `pkg` to match the GZ.

**Comment by idodeclare** [comment]
Regarding `lipkg`, Dan McD wrote "some packages (like system/library) have explicit parent-image dependencies." Do you mean to include `pkg` in that particular set of packages?

**Comment by danmcd** [comment]
A parent dependency is spelled out using a special dependency.  See here:

https://github.com/omniosorg/illumos-omnios/commit/45863a2b11c40871b34f698699fa3ad1c534861c#diff-b14f4962d48b570e4f38165b7b0118c1

e.g.

**Comment by idodeclare** [comment]
I see. Thank you.

**Comment by citrus-it** [comment]
This is fixed in bloody and will be fixed in the r151026i release scheduled for w/c 2.7.2018
