### ISSUE TITLE
bloody: zones do not shut down properly.

### ISSUE THREAD

**Issue by citrus-it** [omniosorg/illumos-omnios#18]
>Date: Fri, 21 Jul 2017 08:22:51 +0000
From: Jim Klimov
To: OmniOS-discuss
Subject: [OmniOS-discuss] Local zone regression in CE bloody

>Hi all,

>I have an OmniOS bloody box that was last running 151023. Yesterday I updated it
to latest available original omnios from May 15 or so, and updated that BE to
omniosce bloody. Between the two, zone shutdown stopped working for me (both
ipkg and lx), with the ce variant claiming that "datalinks remain in zone after
shutdown / unable to unconfigure network interfaces in zone / unable to destroy
zone".

>When the zone boots it seems okay and usable, but when trying to halt it -
becomes "down" and I can not change the state (no boot/mount/ready/... options
succeed); killing its zoneadmd and wiping then/var/run/zones also does not help>
>- only GZ reboot.

>Jim

**Comment by citrus-it** [comment]
https://github.com/omniosorg/illumos-omnios/commit/b2519362c825a494fb6e93549e2e32a425011563 is suspect.


```
#!/usr/sbin/dtrace -CZs

#include <sys/dls_mgmt.h>

pid46::dlmgmt_setzoneid:entry
{
        self->p = arg1;
}

pid46::dlmgmt_setzoneid:return
{
        self->pp = (dlmgmt_setzoneid_retval_t *)copyin(arg1,
            sizeof(dlmgmt_setzoneid_retval_t));
        printf("Err: %d\n", self->pp->lr_err);
}
```

```
bloody# lxadm start alpine
bloody# CPU     ID                    FUNCTION:NAME
  1  87694          dlmgmt_setzoneid:return Err: 0
```

```
localhost:~# halt
[Connection to zone 'alpine' pts/2 closed]
bloody#   5  87694          dlmgmt_setzoneid:return Err: 17
```

**Comment by hadfl** [comment]
reverted the referenced commit:
```
boot:
CPU     ID                    FUNCTION:NAME
  2  77539          dlmgmt_setzoneid:return Err: 0

halt:
  2  77539          dlmgmt_setzoneid:return Err: 0
```

will create a PR to revert 8437.

**Comment by citrus-it** [comment]
https://illumos.topicbox.com/groups/developer/discussions/T8ea2034b9360f137

**Comment by citrus-it** [comment]
```
bloody# ./dl.d
dtrace: script './dl.d' matched 3 probes
CPU     ID                    FUNCTION:NAME
  6  88316           dlmgmt_setzoneid:entry
              dlmgmtd`dlmgmt_setzoneid
              dlmgmtd`dlmgmt_handler+0x96
              libc.so.1`__door_return+0x3d
Zone ID: 0
New zone id: 0

  6  88318          dlmgmt_setzoneid:return
Old zone id: 1
Err: 17
```

**Comment by hadfl** [comment]
reverted in `illumos-gate`: https://github.com/illumos/illumos-gate/commit/0617d817b9a6060d315f707868c15f8e9e78a6c7
