### ISSUE TITLE
Small typo in zlogin man page

### ISSUE THREAD

**Issue by priyadarshan** [omniosorg/illumos-omnios#224]
"Standalone-processs Interactive Mode" should perhaps be "Standalone-process Interactive Mode"
https://github.com/omniosorg/illumos-omnios/blob/master/usr/src/man/man1/zlogin.1#L87

**Comment by citrus-it** [comment]
Thanks - this fix is queued and should be merged in the next day or two.

**Comment by priyadarshan** [comment]
Thank you. I have encountered some other mistypes along the way, but didn't want to bother you here. Perhaps I'll report them directly, or just let them be.
