### ISSUE TITLE
grep dumps core with -C -B flags

### ISSUE THREAD

**Issue by priyadarshan** [omniosorg/illumos-omnios#229]
Using built-in `grep` with `-C` or -`B` flags dumps core.

```root@omnios:~# uname -a
SunOS itstore.vsm.in 5.11 omnios-r151026-673c59f55d i86pc i386 i86pc Solaris
root@omnios:~# which grep
/usr/bin/grep
root@omnios:~# which ggrep
/usr/bin/ggrep
```

Test:

```
root@omnios:~# /usr/sbin/prtconf -v | grep -A 1 "6535/b"
            value='id1,kdev@w0025385971b16535/b'
        name='keyboard-layout' type=string items=1
Segmentation Fault (core dumped)
```

Same if the flags are implicit:

```
root@omnios:~# /usr/sbin/prtconf -v | grep -1 "6535/b"
            value='id1,kdev@w0025385971b16535/b'
        name='keyboard-layout' type=string items=1
Segmentation Fault (core dumped)
```

`ggrep` seems to be fine:

```
root@omnios:~# /usr/sbin/prtconf -v | ggrep -1 "6535/b"
        name='diskdevid' type=string items=1
            value='id1,kdev@w0025385971b16535/b'
        name='keyboard-layout' type=string items=1
```

If you wish, I can file report on illumos.org tracker, but I have no way to check this on other illumos-based OS.

**Comment by citrus-it** [comment]
I'm guessing that this is fixed by https://github.com/omniosorg/illumos-omnios/commit/d9241f995480d9097812b34500484c0fff9d7528 which is in our bloody branch but has not been backported to r151026.

We'll schedule it for backport in the next release which is currently slated for a couple of weeks.

**Comment by citrus-it** [comment]
This fix will be included in `r151026i` which is scheduled for release w/c 2.7.2018

If you do decide to use bloody, just bear in mind that it is a development release which changes often and sometimes contains known bugs. We do backport fixes from bloody to the other supported releases but this one slipped through.

**Comment by priyadarshan** [comment]
> If you do decide to use bloody, just bear in mind that it is a development release which changes often and sometimes contains known bugs. We do backport fixes from bloody to the other supported releases but this one slipped through.

Thank you for the note. I will use stable for now. 

Thank you for all the very hard work you and others put in to OmniOS. OmniOS is marvellous. I only wish I would have discovered it sooner.
