### ISSUE TITLE
pkg:/archiver/gnu-tar missing dependency

### ISSUE THREAD

**Issue by RantyDave** [omniosorg/illumos-omnios#25]
pkg:/archiver/gnu-tar has a dependency on pkg:/compress/gzip (needs it for gzcat) which is not part of the manifest. I can't see the manifest in the source tree...

**Comment by jfqd** [comment]
gnu-tar is part of omnios-build and not of illumos-omnios. You can find the manifest here: https://github.com/omniosorg/omnios-build/blob/master/build/gtar/build.sh

**Comment by hadfl** [comment]
fixed: https://github.com/omniosorg/omnios-build/pull/109

thanks for reporting.
