### ISSUE TITLE
slow NFS writes in 151026

### ISSUE THREAD

**Issue by discard-this** [omniosorg/illumos-omnios#256]
I recently installed a new host. So new I couldn't install LTS on it so I've installed 151026.

This host is strictly for serving ZFS-based NFS & CIFS. Everything else is just default.

Over time it has become fairly obvious to me that NFS writes are ... well, abysmal.

This example is copying a 36GB directory of mixed size/type files. The first copy is strictly on a filesystem on the new server. The second is reading from the new server to an existing one. The third is doing the same read/write activity as test one but on an existing server running 151022. 

on new fileserver:

: || nomad@omics1 fs2test ; time cp -rp 004test omics1/004test-1

real	22m27.225s
user	0m0.188s
sys	0m29.880s

reading from new fileserver, writing to existing fileserver:

: || nomad@omics1 hvfs2test ; time cp -rp /misc/fs2test/004test .

real	2m9.770s
user	0m0.180s
sys	0m28.694s

existing fileserver:

: || nomad@omics1 hvfs2test ; time cp -rp 004test omics1/004test-1

real	2m14.158s
user	0m0.242s
sys	0m30.313s

While the user and system times are consistent across all tests the wall clock time of the first test is 10x that of the others. I've seen wall clock time on these tests take as long as 50 minutes. All tests were done on the same CentOS 7 host.

Watching snoop collect packets I see multiple-minutes-long pauses while writing to the new server. If I'm reading the heat maps right - https://drive.google.com/open?id=1zcX9ryXjrPMH0_uUbfywiTTnJDau4WW0 - it seems to be spending about 81% of its time in _t_cancel, waiting on a thread to cancel. I'm not a dev, haven't looked at the code, so it's quite possible I'm misunderstanding what the map is saying.

The client spends a lot of time so stuck in diskwait that it can take several minutes to respond after a SIGINT, SIGHUP, or SIGKILL to the cp process.

nomad

**Comment by discard-this** [comment]
I forgot to say that local writes on the file server are speedy, roughly 2 minutes for the 36GB test.

Also,

  pool: pool0
 state: ONLINE
  scan: none requested
config:

        NAME                         STATE     READ WRITE CKSUM
        pool0                        ONLINE       0     0     0
          raidz2-0                   ONLINE       0     0     0
            c0t5000C500A612DA93d0    ONLINE       0     0     0
            c0t5000C500957D4A93d0    ONLINE       0     0     0
            c0t5000C500957D4C1Bd0    ONLINE       0     0     0
            c0t5000C500957D25B3d0    ONLINE       0     0     0
            c0t5000C500957D27F3d0    ONLINE       0     0     0
            c0t5000C500957D2553d0    ONLINE       0     0     0
        logs
          mirror-1                   ONLINE       0     0     0
            c0t55CD2E414EC0FF43d0s0  ONLINE       0     0     0
            c3t0d0s0                 ONLINE       0     0     0
        cache
          c0t55CD2E414EC0FF43d0s1    ONLINE       0     0     0
          c3t0d0s1                   ONLINE       0     0     0
        spares
          c0t5000C50095722E27d0      AVAIL   

errors: No known data errors

**Comment by discard-this** [comment]
The flame graph was generated using the script from http://www.brendangregg.com/FlameGraphs/cpuflamegraphs.html#DTrace - replacing "mysqld" with "nfsd". I tried to attach the output files from the three stages here but it doesn't seem to want to accept those file types. I've dropped them on the SFTP server that Andy has access to.

**Comment by oetiker** [comment]
I created this little 'test' script to see what my system does.

```perl
#!/usr/bin/perl
# write 1000 files of 1MByte of random data
# into the current directory and delete them again after writing

use Time::HiRes;

open my $rand, "<",'/dev/urandom';
my $big;
sysread $rand,$big,1e6;
my $count =0;
sub make_file {
    my $dir = "dir".rand(100000);
    mkdir $dir;
    my $file = "file".rand(100000);
    open my $fh, ">",$dir."/".$file;
    print $fh $big;
    close $fh;
    return [$dir,$file];
}

my $start = Time::HiRes::time;
my @stack;
for (1..1000){
    push @stack, make_file();
    print STDERR $count++,"\r";
}

my $written = Time::HiRes::time;
while (my $task = shift @stack){
    unlink $task->[0].'/'.$task->[1];
    rmdir $task->[0];
    print STDERR $count--,"\r";
}

my $deleted = Time::HiRes::time;
printf "%.2f MB/s write, %.2f files/s deleted\n", 1000/($written-$start), 1000/($deleted-$written);
```
runnnig this on an kvm host (running on the omnios r26 box) over nfs I get:

50.83 MB/s write, 417.64 files/s deleted

running on locally on omni I get

635.72 MB/s write, 6272.63 files/s deleted

**Comment by BobTB** [comment]
I didn't do any tests yet, but have noticed significant slowdown when using NFS on r26 compared to older versions. iostat shows only 8-10MB/s for S3700 intel SSD as ZIL, when using just the rotating drives the write speed was strangly higher. I nuked the r26 after that, I can not try it again with the same drives to confirm.. but will try to rig something up to test this again and confirm

**Comment by panachoi** [comment]
As I'm seeing similar issues with r22, I'll post data here. I have 2 different pools (backpool, rz2 , internal LSI2008, no zil/l2arc, created on r22; dataPool, rz2 , external LSI2008, SSD zil/l2arc currently disabled, imported from OpenIndiana 151a9) Backpool is ~1/6 the size of dataPool, as it was created specifically for testing, while dataPool the productive (sic!) pool.

Local:
backpool: 469.09 MB/s write, 6598.04 files/s deleted
dataPool: 113.81 MB/s write, 7190.05 files/s deleted

NFS:
backpool: 17.92 MB/s write, 55.30 files/s deleted
dataPool: 4.90 MB/s write, 12.55 files/s deleted

**Comment by oetiker** [comment]
maybe related to #225

**Comment by discard-this** [comment]
I've been doing a bit more profiling. The below numbers reflect tests conducted from a VM on a hypervisor with a 10G link to the same switch as the file servers. The file servers all have trunked 20G (two 10Gs, to be specific) connections. 

fs1 - old server with lots and lots of 1TB spinning rust + SSD ZIL & L2ARC (see below), 24567 Megabytes RAM running omnios-r151022-5e982daae6

hvfs2 - ~18 month old server, two pools (detailed below) of spinning rust + SSD ZIL & L2ARC, 130962 Megabytes RAM, omnios-r151022-89f6242508 (with test patch for kernel panic)

fs2 - new host, one pool of spinning rust + SSD ZIL & L2ARC, 96941 Megabytes RAM, omnios-r151026-51c7d6fd75 - this is the host with the very slow NFS writes.

hvfs2's chrup0 and fs2's pool0 pools are both configured with the same brand/model/size of drives & SSD.

The first two tests were read from one file server, write to another. The third test was read/write to the same pool. The hostname is indicated by name after /misc in the paths.

read from fs1, write to other:
`time cp -rp /misc/fs1test/004test /misc/hvfs2test/omics1

real    1m59.758s
user    0m0.170s
sys     0m28.208s

time cp -rp /misc/fs1test/004test /misc/hvfs2chru/omics1

real    3m11.431s
user    0m0.177s
sys     0m28.030s

time cp -rp /misc/fs1test/004test /misc/fs2test/omics1

real    21m13.412s
user    0m0.188s
sys     0m28.678s`


read from hvfs2test, write to other:
`time cp -rp /misc/hvfs2test/004test /misc/fs1test/omics1/004test-1

real    1m59.881s
user    0m0.228s
sys     0m33.339s

time cp -rp /misc/hvfs2test/004test /misc/hvfs2chru/omics1/004test-1

real    3m5.357s
user    0m0.160s
sys     0m28.000s

time cp -rp /misc/hvfs2test/004test /misc/fs2test/omics1/004test-1

real    20m56.237s
user    0m0.182s
sys     0m27.986s`


read & write from/to same host
`time cp -rp /misc/fs1test/004test /misc/fs1test/omics1/004test-2

real    2m57.745s
user    0m0.244s
sys     0m37.547s

time cp -rp /misc/hvfs2test/004test /misc/hvfs2test/omics1/004test-2

real    2m5.098s
user    0m0.183s
sys     0m32.478s

time cp -rp /misc/hvfs2chru/004test /misc/hvfs2chru/omics1/004test-2

real    3m46.158s
user    0m0.251s
sys     0m39.382s

time cp -rp /misc/fs2test/004test /misc/fs2test/omics1/004test-2

real    29m30.153s
user    0m0.273s
sys     0m38.098s`



fs1 pool:
`  pool: stor1
 state: ONLINE
  scan: scrub repaired 0 in 7h14m with 0 errors on Wed Aug  1 09:27:15 2018
config:

        NAME                         STATE     READ WRITE CKSUM
        stor1                        ONLINE       0     0     0
          raidz1-0                   ONLINE       0     0     0
            c1t5000C5004D2A259Bd0s0  ONLINE       0     0     0
            c1t5000C500408DA4E7d0s0  ONLINE       0     0     0
            c1t5000C5004D2A2D92d0s0  ONLINE       0     0     0
            c1t5000C500407EE41Dd0s0  ONLINE       0     0     0
            c1t5000C5004D2AFDCAd0s0  ONLINE       0     0     0
            c1t5000C500408D9344d0s0  ONLINE       0     0     0
          raidz1-1                   ONLINE       0     0     0
            c1t5000C5004D2A660Ed0    ONLINE       0     0     0
            c1t5000C500407EE794d0    ONLINE       0     0     0
            c1t5000C5004D271BB5d0    ONLINE       0     0     0
            c1t5000C500408D95A9d0    ONLINE       0     0     0
            c1t5000C5004049311Ad0    ONLINE       0     0     0
            c1t5000C5004D2AFE8Dd0    ONLINE       0     0     0
          raidz1-2                   ONLINE       0     0     0
            c1t5000C500408DA596d0    ONLINE       0     0     0
            c1t5000C500407F210Ad0    ONLINE       0     0     0
            c1t5000C5004048F0CCd0    ONLINE       0     0     0
            c1t5000C50014B3047Ed0    ONLINE       0     0     0
            c1t5000C500408DA43Cd0    ONLINE       0     0     0
            c1t5000C500407F12A5d0    ONLINE       0     0     0
          raidz1-3                   ONLINE       0     0     0
            c1t5000C5004D2A3740d0s0  ONLINE       0     0     0
            c1t5000C500408DA4CFd0s0  ONLINE       0     0     0
            c1t5000C5004D29F8EEd0s0  ONLINE       0     0     0
            c1t5000C500408D9321d0s0  ONLINE       0     0     0
            c1t5000C5004D2A6D2Cd0s0  ONLINE       0     0     0
            c1t5000C500873621EFd0p0  ONLINE       0     0     0
          raidz1-4                   ONLINE       0     0     0
            c1t5000C5004D2A9B97d0s0  ONLINE       0     0     0
            c1t5000C500408DA04Bd0s0  ONLINE       0     0     0
            c1t5000C5004D2AFE61d0s0  ONLINE       0     0     0
            c1t5000C5004D2A6B61d0s0  ONLINE       0     0     0
            c1t5000C500407F0238d0s0  ONLINE       0     0     0
            c1t5000C5004D2AB675d0s0  ONLINE       0     0     0
        logs
          mirror-5                   ONLINE       0     0     0
            c3t0d0s0                 ONLINE       0     0     0
            c3t1d0s0                 ONLINE       0     0     0
        cache
          c1t50000F0056424431d0s0    ONLINE       0     0     0
        spares
          c1t5000C5007B2108E9d0p0    AVAIL   
          c1t5000C5007B20FD75d0p0    AVAIL   

errors: No known data errors`


hvfs2 pools:
`  pool: chrup0
 state: ONLINE
  scan: resilvered 3.90T in 216h7m with 0 errors on Wed Aug 22 08:06:25 2018
config:

        NAME                         STATE     READ WRITE CKSUM
        chrup0                       ONLINE       0     0     0
          raidz2-0                   ONLINE       0     0     0
            c6t5000C50094E8F273d0    ONLINE       0     0     0
            c6t5000C50094F6C49Bd0    ONLINE       0     0     0
            c6t5000C50094E591BFd0    ONLINE       0     0     0
            c6t5000C50094E750C3d0    ONLINE       0     0     0
            c6t5000C50094E914BFd0    ONLINE       0     0     0
            c6t5000C50094E75987d0    ONLINE       0     0     0
        logs
          mirror-1                   ONLINE       0     0     0
            c6t55CD2E414EC0CCD3d0s0  ONLINE       0     0     0
            c6t55CD2E414EC15449d0s0  ONLINE       0     0     0
        cache
          c6t55CD2E414EC0CCD3d0s1    ONLINE       0     0     0
          c6t55CD2E414EC15449d0s1    ONLINE       0     0     0
        spares
          c6t5000C50094985FBBd0      AVAIL   

errors: No known data errors

  pool: pool0
 state: ONLINE
  scan: scrub repaired 0 in 4h34m with 0 errors on Sat Aug 25 09:34:54 2018
config:

        NAME                         STATE     READ WRITE CKSUM
        pool0                        ONLINE       0     0     0
          raidz2-0                   ONLINE       0     0     0
            c6t5000C50097659E6Bd0p0  ONLINE       0     0     0
            c6t5000C5009781E913d0p0  ONLINE       0     0     0
            c6t5000C50097827CD7d0p0  ONLINE       0     0     0
            c6t5000C5009781E427d0p0  ONLINE       0     0     0
            c6t5000C5009782783Fd0p0  ONLINE       0     0     0
            c6t5000C500978373E7d0p0  ONLINE       0     0     0
        logs
          mirror-1                   ONLINE       0     0     0
            c2t2d0                   ONLINE       0     0     0
            c2t3d0                   ONLINE       0     0     0
        cache
          c2t4d0                     ONLINE       0     0     0
          c2t5d0                     ONLINE       0     0     0
        spares
          c6t5000C500850FED2Fd0p0    AVAIL   

errors: No known data errors`

fs2 pool:
`  pool: pool0
 state: ONLINE
  scan: scrub in progress since Mon Aug 27 08:28:24 2018
        1.76T scanned out of 1.78T at 1019M/s, 0h0m to go
    0 repaired, 98.61% done
config:

        NAME                         STATE     READ WRITE CKSUM
        pool0                        ONLINE       0     0     0
          raidz2-0                   ONLINE       0     0     0
            c0t5000C500A612DA93d0    ONLINE       0     0     0
            c0t5000C500957D4A93d0    ONLINE       0     0     0
            c0t5000C500957D4C1Bd0    ONLINE       0     0     0
            c0t5000C500957D25B3d0    ONLINE       0     0     0
            c0t5000C500957D27F3d0    ONLINE       0     0     0
            c0t5000C500957D2553d0    ONLINE       0     0     0
        logs
          mirror-1                   ONLINE       0     0     0
            c0t55CD2E414EC0FF43d0s0  ONLINE       0     0     0
            c3t0d0s0                 ONLINE       0     0     0
        cache
          c0t55CD2E414EC0FF43d0s1    ONLINE       0     0     0
          c3t0d0s1                   ONLINE       0     0     0
        spares
          c0t5000C50095722E27d0      AVAIL   

errors: No known data errors

  pool: rpool
 state: ONLINE
  scan: scrub repaired 0 in 0h1m with 0 errors on Wed Aug  1 02:15:01 2018
config:

        NAME        STATE     READ WRITE CKSUM
        rpool       ONLINE       0     0     0
          mirror-0  ONLINE       0     0     0
            c1t4d0  ONLINE       0     0     0
            c1t5d0  ONLINE       0     0     0

errors: No known data errors`

All pools have spinning rust for data storage. SSD for ZIL & L2ARC.

nomad

**Comment by discard-this** [comment]
Running the test script posted here:

fs2:
 `10.99 MB/s write, 258.44 files/s deleted`

hvfs2:
`108.61 MB/s write, 641.07 files/s deleted`

**Comment by discard-this** [comment]
This is a version of an update I just gave to the hardware vendor:

The issues I'm seeing with write speed in 151026 are probably a hardware problem, though it could be a driver problem with the internal controller. 

The host was originally shipped with a single SSD on the internal bus (c3t0d0). We added a second SSD on external bus (c0t55CD2E414EC0FF43d0) and used both for ZIL (s0) & L2ARC (s1), per recommendations from the vendor.

The ZIL is mirrored, the L2ARC is concat.

As a test to see if splitting the drives was the problem I ran the sequence of tests documented in the attachment - .fs2_write_tests_split_zil.txt When I first removed one half of the ZIL and the other half of the L2ARC write speeds went to normal. I added the second drive back to the L2ARC and still had good speed. I then removed the second drive from cache and re-mirrored the ZIL... and speed went back to ultra-slow.

On a hunch, and to prove the false instead of the true, I swapped everything I'd done, using the other drive for ZIL than original, and visa-versa.

Write speed stayed bad. A very clear indication that c3t0d0 was the culprit. 

We just went through the process of moving that drive from internal bus to external, changing c3t0d0 to c0t55CD2E414EC0B5ABd0 in the process.

Write speeds are still good.

Potential implications:
  bad internal controller
  bad internal cable
  OS bug with the internal controller

Root drives are c1t4d0 and c1t5d0 - no idea if that's on the same controller as c3t0d0 or not.However, given we never to NFS writes to rpool that's no way of knowing if they'd have the same problem or not.

The vendor says they are building a host to match the one I have. I expect test results from them shortly and will update this report to say if they do or do not see the same problem with similar hardware.

[fs2_write_tests_split_zil.txt](https://github.com/omniosorg/illumos-omnios/files/2325866/fs2_write_tests_split_zil.txt)

**Comment by discard-this** [comment]
One slightly interesting result, it's still not as fast as the old host, judging by the perl script:

new host:
`: || nomad@omics1 fs2test [1054] ; perl ~/otikertest.perl 
85.42 MB/s write, 455.53 files/s deleted
: || nomad@omics1 fs2test [1055] ; perl ~/otikertest.perl 
84.62 MB/s write, 453.26 files/s deleted
`

old host, same drives & configuration (but a bit more RAM)
`: || nomad@omics1 hvfs2chru [1056] ; perl ~/otikertest.perl 
102.02 MB/s write, 578.61 files/s deleted
: || nomad@omics1 hvfs2chru [1057] ; perl ~/otikertest.perl 
103.40 MB/s write, 539.46 files/s deleted
`

**Comment by discard-this** [comment]
While my particularly spactacularly bad NFS write speed was a hardware problem there is still a NFS write randomly-strange speed problem. 

`: || nomad@omics1 fs2test [1060] ; perl ~/otikertest.perl 
18.34 MB/s write, 445.08 files/s deleted
: || nomad@omics1 fs2test [1061] ; perl ~/otikertest.perl 
87.92 MB/s write, 479.91 files/s deleted
: || nomad@omics1 fs2test [1061] ; perl ~/otikertest.perl 
73.51 MB/s write, 440.22 files/s deleted
: || nomad@omics1 fs2test [1061] ; perl ~/otikertest.perl 
48.70 MB/s write, 424.26 files/s deleted
: || nomad@omics1 fs2test [1061] ; perl ~/otikertest.perl 
87.52 MB/s write, 495.69 files/s deleted
`

**Comment by oetiker** [comment]
and the sever was not under any particular strain at that time I guess? ... you may want to run `zpool iostat -v 2` while the test is running

**Comment by discard-this** [comment]
The server is not in production. I'm the only user putting load on it.

I just tried to duplicate this morning's results and couldn't. 10 runs spanning a gamut of 85.21 MB/s to 89.04 MB/s write.

**Comment by discard-this** [comment]
I did manage to catch a few instances. The attached file is the output of zpool iostat -T d -v 2 run during the following iterations of the perl script.

`Tue Aug 28 14:24:53 PDT 2018
79.05 MB/s write, 437.77 files/s deleted
Tue Aug 28 14:25:18 PDT 2018
82.35 MB/s write, 476.43 files/s deleted
Tue Aug 28 14:25:42 PDT 2018
52.51 MB/s write, 452.49 files/s deleted
Tue Aug 28 14:26:14 PDT 2018
80.12 MB/s write, 468.96 files/s deleted
Tue Aug 28 14:26:38 PDT 2018
80.83 MB/s write, 436.12 files/s deleted
`

I have a much larger file with an hour of such runs if you really want an overdose of data.

nomad

**Comment by BobTB** [comment]
I did some testing of my own, using r26 and r24. I used a Windows system running from NFS share, locally and remotely (esxi). The results are inconclusive. As far as I was able to see, it works more or less the same. 

NFS Local r26 bench

![image](https://user-images.githubusercontent.com/15887688/44816437-94128380-abe2-11e8-9ce2-de0d77f39971.png)

NFS Local r24 bench

![image](https://user-images.githubusercontent.com/15887688/44816475-a7255380-abe2-11e8-8c48-9a5506dc1616.png)

NFS Remote r26 bench

![image](https://user-images.githubusercontent.com/15887688/44816820-a7721e80-abe3-11e8-84aa-0f2737c0b023.png)
![image](https://user-images.githubusercontent.com/15887688/44816842-b35de080-abe3-11e8-8241-10e38bae3736.png)


NFS Remote r24 bench
![image](https://user-images.githubusercontent.com/15887688/44816546-d63bc500-abe2-11e8-8a8f-566fee01944c.png)
