### ISSUE TITLE
Ldap crash causing system to hang (illumos 8543)

### ISSUE THREAD

**Issue by citrus-it** [omniosorg/illumos-omnios#26]
From the mailing list:

```
Date: Mon, 31 Jul 2017 07:05:14 +0000
From: Oliver Weinmann
To: omnios-discuss
Subject: [OmniOS-discuss] Ldap crash causing system to hang fixed in    illumos>

Hi Guys,

I'm currently facing this bug under OmniOS 151022 and I just got informed that
this has been fixed:

https://www.illumos.org/issues/8543

As this bug is causing a complete system hang only a reboot helps. Can this
maybe be implemented?

Best Regards,
Oliver
```

**Comment by hadfl** [comment]
an updated pkg archive is available for testing, containing https://github.com/illumos/illumos-gate/commit/a3bcc60de108dc761615b2b9561d6dc76971f471:
https://downloads.omniosce.org/pkg/system_library_8543.p5p

**Comment by hadfl** [comment]
got feedback from Oliver, that the system is running stable since 3 days. considering it fixed: https://github.com/omniosorg/illumos-omnios/pull/29, https://github.com/omniosorg/illumos-omnios/pull/27
