### ISSUE TITLE
Small svcs(1) fixes for more flexible zones

### ISSUE THREAD

**Issue by hadfl** [omniosorg/illumos-omnios#3]
Thinking about cherry picking the 3 patches mentioned in the mailing list below, as they have (still) not been upstreamed.

https://illumos.topicbox.com/groups/developer/discussions/T8ca4788d89bc77de-Md7dfdeaceadd36b473495e60

Mainly as an exercise and to keep momentum here.

Any objections? @danmcd, do you know by chance if Joyent is still in the process of upstreaming these?

**Comment by danmcd** [comment]
Pick 'em for now, and someone should upstream these for sure.

**Comment by citrus-it** [comment]
Look good to me.

**Comment by hadfl** [comment]
-> https://github.com/omniosorg/illumos-omnios/pull/5
