### ISSUE TITLE
eventfd() failed (38: Function not implemented)

### ISSUE THREAD

**Issue by oetiker** [omniosorg/illumos-omnios#36]
it seems we are missing this patch from our lx https://github.com/joyent/illumos-joyent/commit/662ce04b9d2cbe2db70e6ae61a4da56c584f3a3c

**Comment by citrus-it** [comment]
Was picked for r151019 but something must have gone wrong in the process.

https://github.com/omniosorg/lx-port-data/blob/master/r151019/Jun08/ij-picked-commits#L283

I'll pull it this week.

**Comment by citrus-it** [comment]
It was properly merged but this commit has removed the syscall again.

https://github.com/omniosorg/illumos-omnios/commit/40d65895b6337f60bf151ec9f8479cc29d32ba62

**Comment by citrus-it** [comment]
eventfd() is working for me on a Linux zone on r151022m

```
#include <stdio.h>
#include <sys/eventfd.h>

int
main()
{
        int ret = eventfd(0, 0);
        printf("Ret: %d\n", ret);
        return 0;
}

deb# ./eventfd
Ret: 3
```

**Comment by hadfl** [comment]
working in an `ubuntu-16.04` lx zone on **bloody**, too:
```
ubuntu-16:~# ./eventfd 
Ret: 3

```

**Comment by oetiker** [comment]
@RantyDave can you please test this ?

**Comment by citrus-it** [comment]
Closing as invalid. Can't replicate, no response.
