### ISSUE TITLE
bhhwcompat throw error Cannot open /dev/vmmctl: No such file or directory

### ISSUE THREAD

**Issue by MoiMemePerso** [omniosorg/illumos-omnios#429]
Tested on two installations with omnios-r151028-3aeadc46d9
Bhyve is no working on both systems, and when I use the bhhwcompat  -v command to check compatibility, it throw this error: Cannot open /dev/vmmctl: No such file or directory

**Comment by citrus-it** [comment]
That looks like the kernel module is not loaded for some reason. Can you try the following steps to diagnose?

Check that the package is installed (I assume it is since you have the `bhhwcompat` command).
```
r151028# pkg list system/bhyve
NAME (PUBLISHER)                                  VERSION                    IFO
system/bhyve                                      0.5.11-151028.0            i--
```

Check if the module is loaded:

```
r151028# modinfo | grep vmm
259 fffffffff8348000 23a8f8 278   1  vmm (vmm)
```

Check the logs to see if any errors are reported:

```
r151028# dmesg | egrep -i 'vmm|bhyve'
```

**Comment by MoiMemePerso** [comment]
I just checked, I got the same bhyve version
`XST-12H:~# pkg list system/bhyve
NAME (PUBLISHER)                                  VERSION                    IFO
system/bhyve                                      0.5.11-151028.0            i--`

But the vmm module isn't loaded automatically at boot.
If I load it manually using `modload -p drv/amd64/vmm`, the module is properly loaded:
`XST-12H:~# modinfo | grep vmm
182 fffffffff8139000 23a8f8 276   1  vmm (vmm)`

I don't get any error message regarding vmm or bhyve, the command `dmesg | egrep -i 'vmm|bhyve'` returns nothing.

Even after loading the module manually, I still got the same error
`XST-12H:~# bhhwcompat -v
Cannot open /dev/vmmctl: No such file or directory`

I uninstalled bhyve pakage, rebooted and installed it again, same problem.
FYI, the vmm module is loaded right after bhyve installation, but not after a reboot. I can still load it manually.

**Comment by sstillwell** [comment]
For what it's worth, this still appears to be an issue with latest stable.

`scott@omniosce:~$ sudo pkg install system/bhyve
Password:
No updates necessary for this image.
scott@omniosce:~$ sudo bhhwcompat -v
Cannot open /dev/vmmctl: No such file or directory
scott@omniosce:~$ pkg list system/bhyve
NAME (PUBLISHER)                                  VERSION                    IFO
system/bhyve                                      0.5.11-151032.0            i--
scott@omniosce:~$ modinfo | grep vm
scott@omniosce:~$ pfexec modload -p drv/amd64/vmm
scott@omniosce:~$ modinfo | grep vm
206 fffffffff8033000 13bbd8 279   1  vmm (bhyve vmm)
scott@omniosce:~$ pfexec bhhwcompat -v
Cannot open /dev/vmmctl: No such file or directory
scott@omniosce:~$ sudo bhhwcompat -v
Password:
Cannot open /dev/vmmctl: No such file or directory
scott@omniosce:~$`

**Comment by stellarpower** [comment]
Do we know what minimum requirements there are for being able to run bhyve under a virtualised installation of Omni? I am playing around with Illumos under my usual Linux in Virtualbox. I have just updated to Virtualbox 6.1, which *supposedly* supports nested vt-X for 5th-gen and above Intel i-range CPUs, yet I am getting the same error as above. Grepping through dmesg I have `vmx_init processor does not support desired primary processor-based controls` - will the requirements be the same as for a general bhyve running on BSD or is there a certain set of features bhyve on Illumos needs? (I ask, however I am not necessarily convinced Virtualbox *is* passing through the nested virtualisation support, this is apparently a) a new feature b) one that the GUI doesn't support perfectly and c) only tested for running Virtualbox in the first-level guest.)
