### ISSUE TITLE
Hyper-V 18343 causing system to hang (r151030 LTS)

### ISSUE THREAD

**Issue by jack23247** [omniosorg/illumos-omnios#459]
The system hangs on "Configuring devices" on Hyper-V 18343, in a Gen1 machine. Upon enabing verbose boot, it looks like the Hyper-V interface is recognized but then it just stops. 
I've described the issue in a more verbose way [in this article](https://jack23247.github.io/blog/sysadm/installing-omnios-hyperv/).

Here is the tail of the boot log with verbose boot enabled:
![hypercall](https://user-images.githubusercontent.com/35559767/57765806-7486a100-7706-11e9-8742-85d7f09692eb.png)

**Comment by citrus-it** [comment]
Thanks for the report. As you discovered, Gen2 machines are not currently supported, although we have work in-progress to address that in a future release.

A number of our developers are successfully running OmniOS under hyper-v on Windows 10 so, even though it's a beta feature, it should work for you.

Ideally we need to get the stack trace at the point that it's hung. To do this, I usually create a virtual serial port called `console` and attach PuTTY to that (via serial to `\\.\pipe\console` - run PuTTY as administrator) then set the console and OS console to ttya via the loader menu. Also select `kmdb` and `debug` as well as `verbose` from the loader menu and then boot until you drop to the `kmdb` prompt.

Set up a breakpoint on receiving an NMI and continue.

```
::bp apic_nmi_intr
::cont
```

Once it's hung, send an NMI from powershell

```
Debug-VM -Name "VM Name" -InjectNonMaskableInterrupt 
```

and you should drop back to the kmdb prompt.

Here, get a stack trace for the current thread with `$C`, or a summary for all threads with `::stacks`
The reason to use a serial port is to make it possible to scroll back and copy/paste.

**Comment by jack23247** [comment]
You're welcome! I'm glad I can help.

Tried your ingenious procedure, but I got this:
```
module /platform/i86pc/kernel/amd64/unix: text at [0xfffffffffb800000, 0xfffffffffb982fa9] data at 0xfffffffffbc00000
module /kernel/amd64/genunix: text at [0xfffffffffbcad840, 0xfffffffffbf3cc67] data at 0xfffffffffbf3cc80
Loading kmdb...
module /kernel/misc/amd64/kmdbmod: text at [0xfffffffffb982fc0, 0xfffffffffba42067] data at 0xfffffffffbffe440
module /kernel/misc/amd64/ctf: text at [0xfffffffffba42080, 0xfffffffffba4f2e7] data at 0xfffffffffc0378a0

Welcome to kmdb
kmdb: unable to determine terminal type: assuming `vt100'
Loaded modules: [ unix krtld genunix ]
[0]> ::bp apic_nmi_intr
kmdb: failed to add breakpoint at apic_nmi_intr: unknown symbol name
[0]>
```

**Comment by citrus-it** [comment]
Ah, sorry, try:

```
::bp pcplusmp`apic_nmi_intr
```

(notice the backtick)

**Comment by jack23247** [comment]
Flawless. 
Here's the [log](https://github.com/omniosorg/illumos-omnios/files/3182336/omnios.log)!

**Comment by citrus-it** [comment]
How many virtual CPUs do you have configured? OmniOS currently requires more than one.

**Comment by jack23247** [comment]
Thank you for helping me out: I had configured the machine with one VCPU only, now it seems to work fine with two.

Sorry for bringing up a non-issue: is it written anywhere on the docs though that 2 VCPUS are required? I reckon it works fine in VirtualBox with one. Also, is there a reason for requiring two VCPUs? 

Keep up the good work!

**Comment by citrus-it** [comment]
Great. The requirement for >1 vCPUs is a known bug that we're working on, it looks like it was not documented in the release notes, I'll fix that.

**Comment by gbulfon** [comment]
Hello, I tried replicating all your changes for Hyper-V and Gen2 to my illumos gate, but my iso always hangs after :

```
hv_vmbus0: vmbus IDT vector 248
hv_vmbus0: SINT val 200f8

```
while your latest iso on the same VM goes on showing version.
Looks like it cannot attach to vmbus.
I tried your NMI trick to check the stack while hanging there, but even adding the bp, after sending the NMI from PowerShell the system panics and reboot, and the serial consolo just shows this:

```
panic[cpu0]/thread=fffffe0007a05c20: NMI received


Warning - stack not written to the dump buffer
fffffffffbc14ed0 fffffffff38eb323 ()
fffffffffbc14f00 unix:av_dispatch_nmivect+32 ()
fffffffffbc14f10 unix:nmiint+155 ()
fffffe0007a05ba0 unix:mach_cpu_idle+b ()
fffffe0007a05bd0 unix:cpu_idle+135 ()
fffffe0007a05be0 unix:cpu_idle_adaptive+19 ()
fffffe0007a05c00 unix:idle+3f ()
fffffe0007a05c10 unix:thread_start+b ()

skipping system dump - no dump device configured
rebooting...

```

Any idea what I may be still missing on my illumos gate that may prevent it to attach to the vmbus?
