### ISSUE TITLE
Hang configuring devices under Hyper-V with single guest CPU

### ISSUE THREAD

**Issue by gwr** [omniosorg/illumos-omnios#482]
Installed OmniOS (omniosce-r151030.iso) under Hyper-V on Windows Server 2012r2
With a single guest CPU configured, it boots as far as configuring devices, then hangs.
Work-around: configure at least two guest CPUs.

We'd like single CPU configurations to work too, as that's the default when using the Hyper-V U/I to create a new guest.

**Comment by gwr** [comment]
It looks like the problem here is that  uts/i86pc/os/mp_machdep.c : mach_smpinit()
sets psm_get_ipivect only for multi CPU systems.
```
  psm_get_ipivect = pops->psm_get_ipivect;
```
Let's try moving that above the "return if single CPU".

**Comment by danmcd** [comment]
Commenting to get notifications...

**Comment by citrus-it** [comment]
This is verified as fixed by #490 and #483
