### ISSUE TITLE
kernel panic on halt - BAD TRAP: type=e (#pf Page fault) rp=fffffe00b6e59b50 addr=0 occurred in module "usba" due to a NULL pointer dereference

### ISSUE THREAD

**Issue by discard-this** [omniosorg/illumos-omnios#632]
SunOS hvfs2 5.11 omnios-r151030-521a1fc4d1 i86pc i386 i86pc

We're using NUT (Network UPS Tool) to monitor our UPSs for power loss. Last week on the 23rd we had an event and the OmniOS hosts started shutting down. However, it seems the newest two (out of 4 total) panic'd on the way down. Both panics were the same. 

As part of a scheduled maintenance window I was testing the NUT config on the 25th and evidently triggered two more panics. Here's the last one from syslog:

Dec 25 10:06:55 chrufs nrpe[522]: [ID 702911 daemon.notice] Caught SIGTERM - shutting down...
Dec 25 10:06:55 chrufs nrpe[522]: [ID 702911 daemon.notice] Daemon shutdown
Dec 25 10:06:55 chrufs pseudo: [ID 129642 kern.info] pseudo-device: pm0
Dec 25 10:06:55 chrufs genunix: [ID 936769 kern.info] pm0 is /pseudo/pm@0
Dec 25 10:06:55 chrufs syslogd: going down on signal 15
Dec 25 10:06:58 chrufs rpcbind: [ID 240694 daemon.error] rpcbind terminating on signal 15.
Dec 25 10:07:02 chrufs genunix: [ID 672855 kern.notice] syncing file systems...
Dec 25 10:07:02 chrufs genunix: [ID 904073 kern.notice]  done
Dec 25 10:07:04 chrufs unix: [ID 836849 kern.notice] 
Dec 25 10:07:04 chrufs ^Mpanic[cpu8]/thread=fffffe83d37b7420: 
Dec 25 10:07:04 chrufs genunix: [ID 335743 kern.notice] BAD TRAP: type=e (#pf Page fault) rp=fffffe00b6e59b50 addr=0 occurred in module "usba" due to a NULL pointer dereference
Dec 25 10:07:04 chrufs unix: [ID 100000 kern.notice] 
Dec 25 10:07:04 chrufs unix: [ID 839527 kern.notice] svc.startd: 
Dec 25 10:07:04 chrufs unix: [ID 753105 kern.notice] #pf Page fault
Dec 25 10:07:04 chrufs unix: [ID 532287 kern.notice] Bad kernel fault at addr=0x0
Dec 25 10:07:04 chrufs unix: [ID 243837 kern.notice] pid=9, pc=0xfffffffff7b87f33, sp=0xfffffe00b6e59c40, eflags=0x10282
Dec 25 10:07:04 chrufs unix: [ID 619397 kern.notice] cr0: 80050033<pg,wp,ne,et,mp,pe>  cr4: 3626f8<smap,smep,osxsav,pcide,vmxe,xmme,fxsr,pge,mce,pae,pse,de>
Dec 25 10:07:05 chrufs unix: [ID 152204 kern.notice] cr2: 0  
Dec 25 10:07:05 chrufs unix: [ID 634440 kern.notice] cr3: 7000000  
Dec 25 10:07:05 chrufs unix: [ID 625715 kern.notice] cr8: f
Dec 25 10:07:05 chrufs unix: [ID 100000 kern.notice] 
Dec 25 10:07:05 chrufs unix: [ID 592667 kern.notice]    rdi:                0 rsi:                0 rdx:                8
Dec 25 10:07:05 chrufs unix: [ID 592667 kern.notice]    rcx:                7  r8:                0  r9:                0
Dec 25 10:07:05 chrufs unix: [ID 592667 kern.notice]    rax: fffffe83d317adc0 rbx:                0 rbp: fffffe00b6e59c60
Dec 25 10:07:05 chrufs unix: [ID 592667 kern.notice]    r10:               e0 r11:                0 r12:                2
Dec 25 10:07:05 chrufs unix: [ID 592667 kern.notice]    r13:                1 r14:                0 r15: fffffe83d2e52d40
Dec 25 10:07:06 chrufs unix: [ID 592667 kern.notice]    fsb:                0 gsb: fffffe83d1c0d000  ds:               4b
Dec 25 10:07:04 chrufs unix: [ID 592667 kern.notice]     es:               4b  fs:                0  gs:              1c3
Dec 25 10:07:04 chrufs unix: [ID 592667 kern.notice]    trp:                e err:                0 rip: fffffffff7b87f33
Dec 25 10:07:04 chrufs unix: [ID 592667 kern.notice]     cs:               30 rfl:            10282 rsp: fffffe00b6e59c40
Dec 25 10:07:04 chrufs unix: [ID 266532 kern.notice]     ss:               38
Dec 25 10:07:04 chrufs unix: [ID 100000 kern.notice] 
Dec 25 10:07:04 chrufs genunix: [ID 655072 kern.notice] fffffe00b6e59a40 unix:real_mode_stop_cpu_stage2_end+c8fc ()
Dec 25 10:07:04 chrufs genunix: [ID 655072 kern.notice] fffffe00b6e59b40 unix:trap+15b1 ()
Dec 25 10:07:04 chrufs genunix: [ID 655072 kern.notice] fffffe00b6e59b50 unix:cmntrap+e6 ()
Dec 25 10:07:05 chrufs genunix: [ID 655072 kern.notice] fffffe00b6e59c60 usba:usb_console_input_enter+13 ()
Dec 25 10:07:05 chrufs genunix: [ID 655072 kern.notice] fffffe00b6e59c80 hid:hid_polled_input_enter+18 ()
Dec 25 10:07:05 chrufs genunix: [ID 655072 kern.notice] fffffe00b6e59ca0 usbkbm:usbkbm_polled_enter+42 ()
Dec 25 10:07:05 chrufs genunix: [ID 655072 kern.notice] fffffe00b6e59cd0 conskbd:conskbd_polledio_enter+38 ()
Dec 25 10:07:05 chrufs genunix: [ID 655072 kern.notice] fffffe00b6e59cf0 wc:wc_polled_enter+24 ()
Dec 25 10:07:05 chrufs genunix: [ID 655072 kern.notice] fffffe00b6e59d00 genunix:prom_poll_enter+1f ()
Dec 25 10:07:05 chrufs genunix: [ID 655072 kern.notice] fffffe00b6e59d10 genunix:prom_exit_to_mon+9 ()
Dec 25 10:07:06 chrufs genunix: [ID 655072 kern.notice] fffffe00b6e59d40 unix:kdi_isr_end+4873 ()
Dec 25 10:07:06 chrufs genunix: [ID 655072 kern.notice] fffffe00b6e59da0 unix:mdboot+116 ()
Dec 25 10:07:04 chrufs genunix: [ID 655072 kern.notice] fffffe00b6e59e30 genunix:kadmin+446 ()
Dec 25 10:07:04 chrufs genunix: [ID 655072 kern.notice] fffffe00b6e59eb0 genunix:uadmin+16d ()
Dec 25 10:07:04 chrufs genunix: [ID 655072 kern.notice] fffffe00b6e59f10 unix:brand_sys_syscall32+1aa ()
Dec 25 10:07:04 chrufs unix: [ID 100000 kern.notice] 
Dec 25 10:07:04 chrufs genunix: [ID 111219 kern.notice] dumping to /dev/zvol/dsk/rpool/dump, offset 65536, content: kernel + curproc
Dec 25 10:07:04 chrufs ahci: [ID 405573 kern.info] NOTICE: ahci0: ahci_tran_reset_dport port 4 reset port
Dec 25 10:07:04 chrufs ahci: [ID 405573 kern.info] NOTICE: ahci0: ahci_tran_reset_dport port 5 reset port
Dec 25 10:07:04 chrufs genunix: [ID 100000 kern.notice] 
Dec 25 10:07:04 chrufs genunix: [ID 665016 kern.notice] ^M100% done: 1296002 pages dumped, 
Dec 25 10:07:04 chrufs genunix: [ID 851671 kern.notice] dump succeeded

I didn't realize it at the time (because powerloss) so I didn't grab a savecore. However, it is possible the hosts never needed to swap so I did a savecore -v now and it didn't give any errors.

[[[[,,,savecore -v 
,,,SunOS chrufs 5.11 omnios-r151030-521a1fc4d1 i86pc
,,,Crash dump time Wed Dec 25 10:07:04 2019

,,,/var/crash/chrufs/vmdump.0
Metrics:
Master cpu_seqid,8
Master cpu_id,8
dump_flags,0x4000b
dump_ioerr,0
Helpers:
,,000,   *   *   *   *   *   *   *   *   M   *   *   *   *   *   *   *
ncbuf_used,1
ncmap,1
Found 4M ranges,0
Found small pages,0
Compression level,0
Compression type,serial lzjb
Compression ratio,6.24
nhelper_used,1
Dump I/O rate MBS,63.90
..total bytes,849408000
..total nsec,13291674186
dumpbuf.iosize,131072
dumpbuf.size,131072
Dump pages/sec,48000
Dump pages,1296002
Dump time,27
per-cent map utilization,87

Per-page metrics:
bitmap nsec/page,14
map nsec/page,0
unmap nsec/page,1
copy nsec/page,1596
compress nsec/page,6462
write nsec/page,9675
inwait nsec/page,0
outwait nsec/page,0
freebufq.empty,0
helperq.empty,0
writerq.empty,0
mainq.empty,17828
I/O wait nsec/page,4134558

Copy pages,1296002
Copy time,4
Copy pages/sec,324000
]]]]

What, if any, information would you like me to try to pull from the cores?

nomad

**Comment by citrus-it** [comment]
Hi, a stack trace with parameters would be useful, so can you post the output of these mdb commands against the core please?

```
::status
::stackregs
```

**Comment by discard-this** [comment]
first host:

> ::status
debugging crash dump vmcore.0 (64-bit) from chrufs
operating system: 5.11 omnios-r151030-521a1fc4d1 (i86pc)
image uuid: cb6e4932-f2ce-684c-e233-b7c71943edaa
panic message: BAD TRAP: type=e (#pf Page fault) rp=fffffe00b6e59b50 addr=0 occurred in module "usba" due to a NULL pointer dereference
dump content: kernel pages and pages from PID -1
> ::stackregs
fffffe00b6e59c60 usb_console_input_enter+0x13(0)
fffffe00b6e59c80 hid_polled_input_enter+0x18(fffffe83d2e5d300)
fffffe00b6e59ca0 usbkbm_polled_enter+0x42(fffffe83d317adc0)
fffffe00b6e59cd0 conskbd_polledio_enter+0x38(ffffffffc00e8a60)
fffffe00b6e59cf0 wc_polled_enter+0x24(ffffffffc00e5e80)
fffffe00b6e59d00 prom_poll_enter+0x1f()
fffffe00b6e59d10 prom_exit_to_mon+9()
fffffe00b6e59d40 0xfffffffffb84c873()
fffffe00b6e59da0 mdboot+0x116(2, 0, 0, 1)
fffffe00b6e59e30 kadmin+0x446(2, 0, 0, fffffe83b2120cf8)
fffffe00b6e59eb0 uadmin+0x16d(2, 0, 0)
fffffe00b6e59f10 sys_syscall32+0x12f()

second host:

> ::status
debugging crash dump vmcore.0 (64-bit) from hvfs2
operating system: 5.11 omnios-r151030-521a1fc4d1 (i86pc)
image uuid: 7c36c3e4-b81d-c49c-9701-fce425e607b7
panic message: BAD TRAP: type=e (#pf Page fault) rp=fffffe00f53b9b50 addr=0 occurred in module "usba" due to a NULL pointer dereference
dump content: kernel pages only
> ::stackregs
fffffe00f53b9c60 usb_console_input_enter+0x13(0)
fffffe00f53b9c80 hid_polled_input_enter+0x18(fffffeb1cea95d80)
fffffe00f53b9ca0 usbkbm_polled_enter+0x42(fffffeb1cd2152c0)
fffffe00f53b9cd0 conskbd_polledio_enter+0x38(ffffffffc00e8a60)
fffffe00f53b9cf0 wc_polled_enter+0x24(ffffffffc00e5e80)
fffffe00f53b9d00 prom_poll_enter+0x1f()
fffffe00f53b9d10 prom_exit_to_mon+9()
fffffe00f53b9d40 0xfffffffffb84c873()
fffffe00f53b9da0 mdboot+0x116(2, 0, 0, 1)
fffffe00f53b9e30 kadmin+0x446(2, 0, 0, fffffeb1ae315cf8)
fffffe00f53b9eb0 uadmin+0x16d(2, 0, 0)
fffffe00f53b9f10 sys_syscall32+0x12f()

**Comment by citrus-it** [comment]
On the first host, please do:

```
fffffe83d2e5d300::print -at hid_state_t
```

**Comment by discard-this** [comment]
> fffffe83d2e5d300::print -at hid_state_t
fffffe83d2e5d300 hid_state_t {
    fffffe83d2e5d300 dev_info_t *hid_dip = 0xfffffe83b234dd50
    fffffe83d2e5d308 kmutex_t hid_mutex = {
        fffffe83d2e5d308 void *[1] _opaque = [ 0 ]
    }
    fffffe83d2e5d310 int hid_instance = 0x2
    fffffe83d2e5d314 int hid_attach_flags = 0x3
    fffffe83d2e5d318 int hid_dev_state = 0x1
    fffffe83d2e5d31c int hid_default_pipe_req = 0
    fffffe83d2e5d320 hid_power_t *hid_pm = 0xfffffe83d3184f00
    fffffe83d2e5d328 usb_client_dev_data_t *hid_dev_data = 0
    fffffe83d2e5d330 usb_dev_descr_t *hid_dev_descr = 0xfffffe83d2f85e70
    fffffe83d2e5d338 int hid_interfaceno = 0
    fffffe83d2e5d33c usb_if_descr_t hid_if_descr = {
        fffffe83d2e5d33c uint8_t bLength = 0x9
        fffffe83d2e5d33d uint8_t bDescriptorType = 0x4
        fffffe83d2e5d33e uint8_t bInterfaceNumber = 0
        fffffe83d2e5d33f uint8_t bAlternateSetting = 0
        fffffe83d2e5d340 uint8_t bNumEndpoints = 0x1
        fffffe83d2e5d341 uint8_t bInterfaceClass = 0x3
        fffffe83d2e5d342 uint8_t bInterfaceSubClass = 0x1
        fffffe83d2e5d343 uint8_t bInterfaceProtocol = 0x1
        fffffe83d2e5d344 uint8_t iInterface = 0
    }
    fffffe83d2e5d346 usb_hid_descr_t hid_hid_descr = {
        fffffe83d2e5d346 uchar_t bLength = 0x9
        fffffe83d2e5d347 uchar_t bDescriptorType = 0x21
        fffffe83d2e5d348 ushort_t bcdHID = 0x100
        fffffe83d2e5d34a uchar_t bCountryCode = 0
        fffffe83d2e5d34b uchar_t bNumDescriptors = 0x1
        fffffe83d2e5d34c uchar_t bReportDescriptorType = 0x22
        fffffe83d2e5d34e ushort_t wReportDescriptorLength = 0x40
    }
    fffffe83d2e5d350 usb_ep_xdescr_t hid_ep_intr_xdescr = {
        fffffe83d2e5d350 uint_t uex_version = 0x1
        fffffe83d2e5d354 usb_ep_xdescr_flags_t uex_flags = 0 (0)
        fffffe83d2e5d358 usb_ep_descr_t uex_ep = {
            fffffe83d2e5d358 uint8_t bLength = 0x7
            fffffe83d2e5d359 uint8_t bDescriptorType = 0x5
            fffffe83d2e5d35a uint8_t bEndpointAddress = 0x81
            fffffe83d2e5d35b uint8_t bmAttributes = 0x3
            fffffe83d2e5d35c uint16_t wMaxPacketSize = 0x8
            fffffe83d2e5d35e uint8_t bInterval = 0xa
        }
        fffffe83d2e5d360 usb_ep_ss_comp_descr_t uex_ep_ss = {
            fffffe83d2e5d360 uint8_t bLength = 0
            fffffe83d2e5d361 uint8_t bDescriptorType = 0
            fffffe83d2e5d362 uint8_t bMaxBurst = 0
            fffffe83d2e5d363 uint8_t bmAttributes = 0
            fffffe83d2e5d364 uint16_t wBytesPerInterval = 0
        }
    }
    fffffe83d2e5d368 hidparser_handle_t hid_report_descr = 0xfffffe83d28151e8
    fffffe83d2e5d370 usb_pipe_handle_t hid_default_pipe = 0xfffffe83d2ec10a8
    fffffe83d2e5d378 usb_pipe_handle_t hid_interrupt_pipe = 0xfffffe83d2ec1460
    fffffe83d2e5d380 int hid_packet_size = 0x8
    fffffe83d2e5d384 usb_pipe_policy_t hid_intr_pipe_policy = {
        fffffe83d2e5d384 uchar_t pp_max_async_reqs = 0x1
    }
    fffffe83d2e5d388 usb_console_info_t hid_polled_console_info = 0
    fffffe83d2e5d390 uchar_t *hid_polled_raw_buf = 0
    fffffe83d2e5d398 usb_log_handle_t hid_log_handle = 0xfffffe83d2f83bd0
    fffffe83d2e5d3a0 queue_t *hid_internal_rq = 0xfffffe83d3180cf8
    fffffe83d2e5d3a8 queue_t *hid_external_rq = 0
    fffffe83d2e5d3b0 queue_t *hid_inuse_rq = 0xfffffe83d3180cf8
    fffffe83d2e5d3b8 int hid_internal_flag = 0x1
    fffffe83d2e5d3bc int hid_external_flag = 0

**Comment by discard-this** [comment]
(Sorry, paste missed the closing "}" - I'm sure you can imagine it being there. :)

**Comment by citrus-it** [comment]
The crash is because `fffffe83d2e5d388 usb_console_info_t hid_polled_console_info = 0`
The question is, why have we ended up here with that set to zero?

**Comment by discard-this** [comment]
Unfortunately, the two hosts this happened on are both in production so I can't test there and my two test hosts didn't exhibit the problem so I can't test there either.

**Comment by discard-this** [comment]
Actually, I think I can schedule downtime for one of the two hosts if that would be useful.

**Comment by discard-this** [comment]
As a note, the shutdown command issued by upsmon was "/usr/sbin/shutdown -y -i 0 -g 0"

**Comment by discard-this** [comment]
Is there any additional information I can provide to move this forward?
