### ISSUE TITLE
Panic after boot menu after upgrading to r151032

### ISSUE THREAD

**Issue by priyadarshan** [omniosorg/illumos-omnios#641]
I have a server we use for testing, Asus X399 motherboard, running OmniOS r151028. After upgrading to r151032, I am experiencing PCI(-X) Express panic right after exiting initial boot menu.

Trying to install r151032 from USB memstick have same results: PCI(-X) Express panic after boot menu.

Server boots fine if, at boot menu, I selecting BE prior to upgrade (on this server, r151028-7).

Server boots also fine by switching off _both_ USB 3.1 controller and illumos-compatible Intel I211-AT network card.

I do not mind losing USB 3.1, but of course network is a must.

I am reporting FYI, just to let you know as curious fact: because same server is working fine with r151028, but throws kernel panic with r151032. You can close this at any time. I will probably end up buying a  new NIC.

**Comment by danmcd** [comment]
If you can get a system dump (/var/crash/*/vmdump.*) please find a way to put it somewhere for folks to inspect?

**Comment by priyadarshan** [comment]
I do not see any file inside /var/crash.

This is what I do to check: after booting to working BE r151028-7,

```
mkdir /mnt/32 # to temporarily mount BE
zfs set mountpoint=/mnt/32 rpool/ROOT/r151032
zfs mount -o ro rpool/ROOT/r151032

ls -ahl /mnt/32/var/crash
total 34
drwx------   2 root     root           2 Sep 15  2018 .
drwxr-xr-x  38 root     sys           38 Jan  9 20:17 ..
```
Note: There is also r151032-1 BE. I checked that as well, one with same results.

**Comment by priyadarshan** [comment]
Trying on different front, I downloaded older installer `Omnis v11 r151028b` and installed it on separate SSD on same server.

- Booting new install as UEFI, it shows same kernel panic
- Booting new install as legacy BIOS works just fine.

The initial SSD, with quite a few older BEs, does not show UEFI boot, I guess because it was installed  before such option was available.

**Comment by priyadarshan** [comment]
I would be very grateful if I could learn how to help debug such kernel panics. Is there a document somewhere I could study?

**Comment by priyadarshan** [comment]
I have posted brief [boot sequence GIF here](https://i.imgur.com/I9gMfHM.mp4).

Screenful was so fast I could not catch very last line:

"skipping system dump - no dump device configured.〃

I guess by now you must have ascertained my absolute beginners status. 😔

**Comment by priyadarshan** [comment]
To wrap this up:

- In the past week we tested the hardware, iust in case issue was there, by booting with FreeBSD 12.1 and doing intense rsync'ing. Also, we tested motherboard and components with Windows based tools. Motherboard, RAM, SAS, disks and NIC are fine according to those.

- So, it seems there is a regression going from `r151028` to `r151032`, at least on this kind of hardware, ie AMD cpu and Intel I211 nic.


At the moment we need to dismantle this server. I can always setup another one in case you need me to test something. Please let me know, I would be glad to help.
