### ISSUE TITLE
dfstab & sharetab - tool validation before edit

### ISSUE THREAD

**Issue by discard-this** [omniosorg/illumos-omnios#666]
I was recently reminded that a path entry in /etc/dfs/dfstab *should not* match one in /etc/dfs/sharetab (and visa versa). I was reminded this when our main file server became unavailable to both NFS and SMB because a filesystem was NFS exported in both places.

It would be useful if the /usr/sbin/share and zfs set share* commands would validate that the entity being shared isn't already in the other config file and exit with error if it is, as a protective measure.

thanks,
nomad

**Comment by danmcd** [comment]
NOTE:  With nfs-zones in -gate, sharefs (sharetab) instantiates per-zone.

**Comment by discard-this** [comment]
Any chance of this being worked on?

thanks,
nomad
