### ISSUE TITLE
Some fixes from OS-6175 would reduce build noise

### ISSUE THREAD

**Issue by ptribble** [omniosorg/illumos-omnios#7]
A current build generates mandoc lint noise from lx.5 and zfd.7d

This is fixed in this commit for illumos-joyent:

https://github.com/joyent/illumos-joyent/commit/4a59c82cb2b671eb549104db3913704c1180d16b#diff-aa688d062b10cee7ba0cd59cea7d7c8d

and the Joyent bugid is OS-6175

We only really want the changes to the two files mentioned, not the other 24 in that commit. (All of the manpages in illumos-gate were fixed before the mandoc update, to eliminate this noise.)

**Comment by citrus-it** [comment]
See PR https://github.com/omniosorg/illumos-omnios/pull/9
I haven't merged from Joyent since their `lx.5` page is somewhat different to ours, but I have fixed up the sentences which don't start on a new line.
