### ISSUE TITLE
Backport to r151030: 10215 lofiadm -la fails after lofiadm -a / lofiadm -d

### ISSUE THREAD

**Issue by andy-js** [omniosorg/illumos-omnios#812]
Is there any chance this fix can be backported to r151030?
https://github.com/illumos/illumos-gate/commit/45ca53447fde2f014d6d62f6bbbfc0b97ae011dd#diff-0319b8ec2cbc2de25a001d9d090f7123

This bug is causing me a lot of grief because as soon as I detach a lofi device after having a labelled device attached previously I'm not able to attach any more.

Thanks.

**Comment by citrus-it** [comment]
It looks like that one is already in r151030, but two followup commits are missing.

commit 9a1bf7f04367a515abcd994451b0991d73dc3148    11043 lofiadm -la still fails after 10215
commit 84ce06cea75304aa6dec12e94975d5372dd9c672    11072 Deadlock in lofi after 11043

I'll back port these for the next reboot release, thanks.

**Comment by citrus-it** [comment]
These backports are in the latest release.
